title: Suganya Ponnusamy
email: suganya.sugu88@gmail.com
description: >
  Suganya Ponnusamy’s developer portfolio showcasing hands-on projects, coding skills, and her journey through application support and software development.

baseurl: ""
url: "https://sugpon.github.io"

github_username: sugpon

theme: jekyll-theme-dinky 

plugins:
  - jekyll-feed
